services:
  mysql:
    image: "mysql:latest"
    environment:
      - "MYSQL_DATABASE=expense"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=verysecret"
      - "MYSQL_USER=myuser"
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
